### ISSUE TITLE
RepRapFirmware V3

### ISSUE THREAD

**Issue by yngndrw** [e3donline/RepRapFirmware-SD#4]
[V3 of RepRapFirmware](https://github.com/dc42/RepRapFirmware/releases/tag/3.0) has just been released with a [whole load of config changes](https://github.com/dc42/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md), so this repository will likely need to be updated.

There are already some settings such as the use of [M558 P7](https://github.com/e3donline/RepRapFirmware-SD/blob/master/sys/config.g#L25) which [is deprecated](https://duet3d.dozuki.com/Wiki/Gcode#Section_M558_in_RepRapFirmware_2_x_and_earlier).

**Comment by e3donline** [comment]
We will be making a RRF3 config in the coming weeks.
